### ISSUE TITLE
Cannot configure network port using jar release

### ISSUE THREAD

**Issue by roboyeti** [lampaa/nvidia-smi-rest#2]
Just found this and think it is a cool project and want to use it to provide a central ruby service access to GPU info across machines in a network.  Not much of a java person, but I have looked thru the code some and tried a few things, but cannot figure out how to configure the port the rest service runs on.  I recreated the resources directory (since I didn't build), including with the application.properties, but it seems to be ignored (perhaps it gets bundled at jar build?).  Is there a way to set the port # with a config file or as an argument at runtime?

**Comment by lampaa** [comment]
Hi, @roboyeti!

Check this: `java -jar file.jar --server.port=8080`
